CREATE MULTISET TABLE MASTER_DB.EMPLOYEE
,NO FALLBACK
,NO BEFORE JOURNAL
,NO AFTER JOURNAL
(
  EMP_ID VARCHAR(20) CHARACTER SET LATIN CASESPECIFIC
 ,EMP_NAME VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC
 ,GENDER CHAR(1) CHARACTER SET LATIN CASESPECIFIC
 ,EMAIL VARCHAR(100) CHARACTER SET LATIN CASESPECIFIC
 ,PHONE VARCHAR(15) CHARACTER SET LATIN CASESPECIFIC
 ,JOINING_DATE DATE FORMAT 'YYYY-MM-DD'
 ,STATE VARCHAR(50) CHARACTER SET LATIN CASESPECIFIC
) PRIMARY INDEX ( EMP_ID );

CREATE TABLE MASTER_DB.EMPLOYEE1 AS MASTER_DB.EMPLOYEE WITH NO DATA;
CREATE TABLE MASTER_DB.EMPLOYEE1 AS MASTER_DB.EMPLOYEE WITH DATA;

ALTER TABLE MASTER_DB.EMPLOYEE
ADD EMP_COUNTRY_CD CHAR(3);

ALTER TABLE MASTER_DB.EMPLOYEE
DROP EMP_COUNTRY_CD;

DROP TABLE MASTER_DB.EMPLOYEE;
