--Giving space to a database.
CREATE DATABASE SPACE_HOLDER FROM MASTER_DB AS PERMANENT = 2000000000;
GIVE SPACE_HOLDER TO CHILD_DB;
DROP DATABASE SPACE_HOLDER;

--Reclaiming space from one database.

CREATE DATABASE SPACE_HOLDER FROM CHILD_DB AS PERMANENT = 2000000000;
GIVE SPACE_HOLDER TO MASTER_DB;
DROP DATABASE SPACE_HOLDER;
