.logon 127.0.0.1/dbc,dbc;

SELECT CURRENT_DATE;

.IF ERRORCODE <> 0 THEN .GOTO FailureHandler;
--.IF ERRORCODE = 0 THEN .GOTO SuccessHandler;
--.IF ACTIVITYCOUNT = 1 THEN .GOTO ShowTime;
.IF ACTIVITYCOUNT <> 0 THEN .GOTO ShowTime;
.IF ACTIVITYCOUNT = 2 THEN .GOTO Err2Dates;
.IF ACTIVITYCOUNT = 0 THEN .GOTO Err0Date;

.QUIT 0;

.LABEL FailureHandler

.QUIT 11;

.LABEL SuccessHandler

.QUIT 1;

.LABEL ShowTime

SELECT CURRENT_TIME;

.QUIT 0;

.LABEL Err2Dates

SELECT 'TWO CURRENT DATES RETURNED';

.QUIT 5;

.LABEL Err0Date

SELECT 'NO CURRENT DATE RETURNED';

.QUIT 5;
