.LOGTABLE MASTER_DB.LG_EMPLOYEE;
.LOGON 127.0.0.1/ABC_ADMIN,ADMIN123;

.SET DB_TARGET_TABLE TO 'MASTER_DB';
.SET DB_WORK_TABLE   TO 'MASTER_DB';
.SET DB_UV_TABLE     TO 'MASTER_DB';
.SET DB_ERROR_TABLE  TO 'MASTER_DB';
.SET TBL_TARGET      TO 'EMPLOYEE';

.BEGIN IMPORT MLOAD
	TABLES      &DB_TARGET_TABLE..&TBL_TARGET
	WORKTABLES  &DB_WORK_TABLE..WT_&TBL_TARGET
	ERRORTABLES &DB_ERROR_TABLE..ET_&TBL_TARGET
		    &DB_UV_TABLE..UV_&TBL_TARGET

SESSIONS 2
SLEEP 5
TENACITY 5;

.LAYOUT IP_FILE_LAYOUT;
.FIELD EMP_ID * VARCHAR(20);
.FIELD EMP_NAME * VARCHAR(100);
.FIELD GENDER * VARCHAR(1);
.FIELD EMAIL * VARCHAR(100);
.FIELD PHONE * VARCHAR(15);
.FIELD JOINING_DATE * VARCHAR(10);
.FIELD STATE * VARCHAR(50);

.DML LABEL INSERT_QUERY;
INSERT INTO &DB_TARGET_TABLE..&TBL_TARGET
(
 EMP_ID = :EMP_ID
,EMP_NAME = :EMP_NAME
,GENDER = :GENDER
,EMAIL = :EMAIL
,PHONE = :PHONE
,JOINING_DATE = CAST(:JOINING_DATE AS DATE)
,STATE = :STATE
);

.IMPORT INFILE /root/Desktop/teradata_quick_reference/data/large_file.txt FROM 2 /*Loading starts from second row*/
	FORMAT VARTEXT '|'
	LAYOUT IP_FILE_LAYOUT
	APPLY INSERT_QUERY;

.END MLOAD;

.LOGOFF &SYSRC;
