.LOGON 127.0.0.1/ABC_ADMIN,ADMIN123;

.PACK 1000
.IMPORT VARTEXT '|' FILE = '/root/Desktop/teradata_quick_reference/data/create_large_file.txt' SKIP = 1;
.REPEAT *
.SET QUIET ON

USING
 EMP_ID       (VARCHAR(20))
,EMP_NAME     (VARCHAR(100))
,GENDER       (VARCHAR(1))
,EMAIL        (VARCHAR(100))
,PHONE        (VARCHAR(15))
,JOINING_DATE (VARCHAR(10))
,STATE        (VARCHAR(50))

INSERT INTO MASTER_DB.EMPLOYEE
(
 EMP_ID
,EMP_NAME
,GENDER
,EMAIL
,PHONE
,JOINING_DATE
,STATE
)
VALUES
(
 :EMP_ID
,:EMP_NAME
,:GENDER
,:EMAIL
,:PHONE
,CAST(:JOINING_DATE AS DATE)
,:STATE
);

.LOGOFF;
