.LOGON 127.0.0.1/ABC_ADMIN,ADMIN123;

.LOGTABLE MASTER_DB.LG_EMPLOYEE;

.BEGIN EXPORT SESSIONS 2;

.EXPORT OUTFILE '/root/Desktop/create_large_file.txt'
	MLSCRIPT '/root/Desktop/create_large_file.sh';

SELECT
CAST(
 EMP_ID
,EMP_NAME
,GENDER
,EMAIL
,PHONE
,JOINING_DATE
,STATE
AS VARCHAR(1000))
FROM MASTER_DB.EMPLOYEE;

.END EXPORT;

.LOGOFF &SYSRC;
