SESSIONS 2;

.LOGON 127.0.0.1/ABC_ADMIN,ADMIN123;

ERRLIMIT 2;
SET RECORD VARTEXT '|';
RECORD 2 /*THRU 10000*/;

BEGIN LOADING      MASTER_DB.EMPLOYEE1
	ERRORFILES MASTER_DB.ET_EMPLOYEE1,
		   MASTER_DB.UV_EMPLOYEE1

CHECKPOINT 100000 /*In Rows*/;

DEFINE
	 EMP_ID       (VARCHAR(20))
	,EMP_NAME     (VARCHAR(100))
	,GENDER       (VARCHAR(1))
	,EMAIL        (VARCHAR(100))
	,PHONE        (VARCHAR(15))
	,JOINING_DATE (VARCHAR(10))
	,STATE        (VARCHAR(50))

FILE = /root/Desktop/teradata_quick_reference/data/create_large_file.txt ;

/*FILE = C:\Users\Guest\Desktop\filename.txt ;*/
/*DDNAME = DATAIN;*/

INSERT INTO MASTER_DB.EMPLOYEE1
(
 EMP_ID
,EMP_NAME
,GENDER
,EMAIL
,PHONE
,JOINING_DATE
,STATE
)
VALUES
(
 :EMP_ID
,:EMP_NAME
,:GENDER
,:EMAIL
,:PHONE
,:JOINING_DATE /*Casting or any other expressions are not allowed in Fastloads*/
,:STATE
);

.END LOADING;

.LOGOFF &SYSRC;
