.LOGTABLE MASTER_DB.LG_EMPLOYEE;
.LOGON 127.0.0.1/ABC_ADMIN,ADMIN123;

.BEGIN LOAD
	ERRORTABLE MASTER_DB.ET_EMPLOYEE
	SESSIONS 2
	SLEEP 5
	TENACITY 5
	ERRLIMIT 2
	CHECKPOINT 10 /*In minutes*/;

.LAYOUT IP_FILE_LAYOUT;
.FIELD EMP_ID * VARCHAR(20);
.FIELD EMP_NAME * VARCHAR(100);
.FIELD GENDER * VARCHAR(1);
.FIELD EMAIL * VARCHAR(100);
.FIELD PHONE * VARCHAR(15);
.FIELD JOINING_DATE * VARCHAR(10);
.FIELD STATE * VARCHAR(50);

.DML LABEL INSERT_QUERY;
INSERT INTO MASTER_DB.EMPLOYEE
(
 EMP_ID
,EMP_NAME
,GENDER
,EMAIL
,PHONE
,JOINING_DATE
,STATE
)
VALUES
(
 :EMP_ID
,:EMP_NAME
,:GENDER
,:EMAIL
,:PHONE
,CAST(:JOINING_DATE AS DATE)
,:STATE
);

.IMPORT INFILE /root/Desktop/teradata_quick_reference/data/create_large_file.txt
	FORMAT VARTEXT '|'
         LAYOUT IP_FILE_LAYOUT
         APPLY INSERT_QUERY;

.END LOAD;

.LOGOFF &SYSRC;
